name: Build and release kernel images

on:
  pull_request:
    paths:
      - 'kernel/**'
    branches: [main]
  push:
    paths:
      - 'kernel/**'
    branches: [main]

defaults:
  run:
    working-directory: kernel

jobs:
  build-cloudhypervisor:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        version: [ 5.15 ]
    env:
      CH_KERNEL_VERSIONS: ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Build kernel
        run: make build-ch
  release-cloudhypervisor:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        version: [ 5.15 ]
    env:
      CH_KERNEL_VERSIONS: ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: |
          make build-ch
          make push-ch